export const STRINGS = {
  transactionCloned: 'Transaction cloned',
  validation: {
    enterAmount: 'Please enter amount',
    selectAccount: 'Please select account',
    selectDestAccount: 'Please select destination account',
    selectCategory: 'Please select category',
    enterPersonName: 'Please enter person name',
    enterDepositName: 'Please enter deposit name',
  },
  duplicate: {
    subcategory: (name: string) => `"${name}" already exists under this parent.`,
    category: (name: string, typeLabel: string) => `"${name}" already exists in ${typeLabel}.`,
    account: 'An account with this name already exists.',
    tag: 'A tag with this name already exists.',
    budget: 'A budget already exists for this category in the selected month.',
    budgetRecurring: 'A recurring budget already exists for this category.',
    budgetCoveredByRecurring: 'A budget already exists for this category in a month covered by this recurring budget.',
    budgetRecurringCoversSelected: 'A recurring budget already covers this category for the selected month.',
    categoryGeneral: 'A category with this name already exists at this level.',
  },
  notes: {
    cashflowHelp: 'Cashflow includes Transfer, Deposit & Loan movements',
  },
  settings: {
    pickers: {
      yearStartTitle: 'Year Start',
      yearStartSubtitle: 'Choose the first month of your year',
      defaultAccountTitle: 'Default Account',
      defaultAccountSubtitle: 'Choose the default account for new transactions',
      currencyTitle: 'Currency',
      currencySubtitle: 'Pick the currency shown across the app',
      themeTitle: 'Theme',
      themeSubtitle: 'Choose how the app follows system appearance',
    },
    biometrics: {
      notSupportedTitle: 'Not Supported',
      notSupportedMessage: 'Your device does not support biometric authentication.',
      notEnrolledTitle: 'Not Enrolled',
      notEnrolledMessage: 'No biometrics are enrolled on this device. Please set up a screen lock or biometrics in your device settings.',
      disablePromptTitle: 'Disable Biometric Lock',
      disablePromptSubtitle: 'Authenticate with your biometrics or device passcode to disable security lock',
      disableFallbackLabel: 'Use Passcode',
      authFailedTitle: 'Authentication Failed',
      authFailedMessage: 'Security lock remains enabled.',
    },
    seeding: {
      successTitle: 'Success',
      successMessage: '1,000 test transactions added.',
      errorTitle: 'Error',
      errorMessage: 'Failed to seed data.',
    },
  },
  backup: {
    alerts: {
      exportFailedTitle: 'Export Failed',
      exportFailedMessage: 'Could not export backup.',
      restoreConfirmTitle: 'Restore Backup',
      restoreConfirmMessage: 'This will replace all current data with the selected backup. You will need to restart the app to complete the restore.\n\nContinue?',
      restoreConfirmLabel: 'Choose File',
      restoreCompleteTitle: 'Restore Complete',
      restoreCompleteMessage: 'Your backup has been restored. The app will now close — reopen it to load your restored data.',
      restoreCompleteConfirmLabel: 'Close App',
      restoreFailedTitle: 'Restore Failed',
      restoreFailedMessage: 'Could not restore backup.',
      folderPickErrorTitle: 'Error',
      folderPickErrorMessage: 'Could not select folder.',
      autoBackupFailedMessage: 'Auto-backup failed because the selected folder is no longer accessible. Tap "Backup Folder" above to re-select it.',
    },
    labels: {
      manualSection: 'Manual',
      autoSection: 'Auto Backup',
      exportCardTitle: 'Export Backup',
      exportLastPrefix: 'Last export:',
      restoreCardTitle: 'Restore Backup',
      restoreLastPrefix: 'Last restore:',
      restoreWarning: 'Restoring replaces all current data.',
      enableAutoBackup: 'Enable Auto Backup',
      autoBackupInfo: 'Runs only when the app is open',
      backupFolder: 'Backup Folder',
      folderPicking: 'Picking folder…',
      folderNotSet: 'Not set — tap to choose',
      backupFrequency: 'Backup Frequency',
      backupsToKeep: 'Backups to Keep',
      lastAutoBackup: 'Last Auto Backup',
      lastAutoBackupNever: 'Never',
    },
  },
  export: {
    alerts: {
      emptyTitle: 'Nothing to Export',
      emptyMessage: 'No transactions match the selected period and account.',
      failedTitle: 'Export Failed',
      failedMessage: 'Could not export CSV.',
      allTimeWarning: 'You are exporting all the data as no filters are selected. Tap again to continue export.',
    },
    labels: {
      title: 'Take your data with you',
      subtitle: 'Export your transactions as a CSV file you can open in any spreadsheet.',
      successTitle: 'Export Complete',
      successSubtitle: (count: number) => `${count} transaction${count === 1 ? '' : 's'} exported to CSV.`,
      exporting: 'Exporting…',
      exportCsv: 'Export CSV',
      exportingDataFor: 'Exporting data for',
      forLabel: 'for',
    },
  },
  reset: {
    labels: {
      warnMessage: 'This will permanently erase all your data on this device.',
      typePrompt: 'Type RESET to continue',
      buttonText: 'Erase Everything',
      cancelText: 'Cancel',
      errorReset: 'Reset failed. Please try again.',
    },
  },
  audit: {
    alerts: {
      errorTitle: 'Error',
      errorGetLogs: 'Failed to retrieve activity logs.',
      errorGetLoanTx: 'Failed to retrieve loan transaction.',
      errorOriginNotFound: 'Origin transaction not found.',
    },
    modal: {
      title: 'Activity Log',
      description: 'You can see the date-wise log of all changes made to your transactions, deposits, loans, and assets over the last 30 days.',
      added: 'Added:',
      addedDesc: 'Newly created items',
      edited: 'Edited:',
      editedDesc: 'Details updated (with diffs)',
      deleted: 'Deleted:',
      deletedDesc: 'Removed items (with details)',
      gotIt: 'Got It',
    },
    empty: {
      title: 'No activity logged yet.',
      subtitle: 'Added, edited, or deleted transactions will show up here.',
    },
  },
};
